
services:
  postgres:
    image: library/postgres:15
    container_name: postgres-db
    ports:
      - 5432:5432
    environment:
       POSTGRES_PASSWORD: 123
       POSTGRES_USER: root
       POSTGRES_DB: emergency-app
    volumes:
      - postgres_db:/var/lib/postgresql/data

  app:
    build: .
    container_name: emergency-app
    ports:
      - 8080:8080
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/emergency-app
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 123

volumes:
  postgres_db:



